// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_test2.Data;

#nullable disable

namespace apbd_test2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_test2.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RaceId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            Date = new DateTime(1980, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location1",
                            Name = "Race1"
                        },
                        new
                        {
                            RaceId = 2,
                            Date = new DateTime(1999, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location2",
                            Name = "Race2"
                        },
                        new
                        {
                            RaceId = 3,
                            Date = new DateTime(2006, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location3",
                            Name = "Race3"
                        });
                });

            modelBuilder.Entity("apbd_test2.Models.RaceParticipation", b =>
                {
                    b.Property<int>("RacerId")
                        .HasColumnType("int");

                    b.Property<int>("TrackRaceId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("RacerId", "TrackRaceId");

                    b.HasIndex("TrackRaceId");

                    b.ToTable("Race_Participation");

                    b.HasData(
                        new
                        {
                            RacerId = 1,
                            TrackRaceId = 1,
                            FinishTimeInSeconds = 13,
                            Position = 2
                        },
                        new
                        {
                            RacerId = 2,
                            TrackRaceId = 2,
                            FinishTimeInSeconds = 16,
                            Position = 1
                        },
                        new
                        {
                            RacerId = 3,
                            TrackRaceId = 3,
                            FinishTimeInSeconds = 12,
                            Position = 1
                        });
                });

            modelBuilder.Entity("apbd_test2.Models.Racer", b =>
                {
                    b.Property<int>("RacerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RacerId");

                    b.ToTable("Racers");

                    b.HasData(
                        new
                        {
                            RacerId = 1,
                            FirstName = "Racer1",
                            LastName = "RacerLast"
                        },
                        new
                        {
                            RacerId = 2,
                            FirstName = "Racer2",
                            LastName = "RacerLast"
                        },
                        new
                        {
                            RacerId = 3,
                            FirstName = "Racer3",
                            LastName = "RacerLast"
                        });
                });

            modelBuilder.Entity("apbd_test2.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<decimal>("LengthInKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrackId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            TrackId = 1,
                            LengthInKm = 12m,
                            Name = "Track1"
                        },
                        new
                        {
                            TrackId = 2,
                            LengthInKm = 14m,
                            Name = "Track2"
                        },
                        new
                        {
                            TrackId = 3,
                            LengthInKm = 15m,
                            Name = "Track3"
                        });
                });

            modelBuilder.Entity("apbd_test2.Models.TrackRace", b =>
                {
                    b.Property<int>("TrackRaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackRaceId"));

                    b.Property<int?>("BestTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Laps")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("TrackRaceId");

                    b.HasIndex("RaceId");

                    b.HasIndex("TrackId");

                    b.ToTable("Track_Race");

                    b.HasData(
                        new
                        {
                            TrackRaceId = 1,
                            BestTimeInSeconds = 12,
                            Laps = 12,
                            RaceId = 1,
                            TrackId = 1
                        },
                        new
                        {
                            TrackRaceId = 2,
                            BestTimeInSeconds = 16,
                            Laps = 14,
                            RaceId = 2,
                            TrackId = 2
                        },
                        new
                        {
                            TrackRaceId = 3,
                            BestTimeInSeconds = 12,
                            Laps = 10,
                            RaceId = 3,
                            TrackId = 3
                        });
                });

            modelBuilder.Entity("apbd_test2.Models.RaceParticipation", b =>
                {
                    b.HasOne("apbd_test2.Models.Racer", "Racer")
                        .WithMany("RaceParticipations")
                        .HasForeignKey("RacerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_test2.Models.TrackRace", "TrackRace")
                        .WithMany("RaceParticipations")
                        .HasForeignKey("TrackRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racer");

                    b.Navigation("TrackRace");
                });

            modelBuilder.Entity("apbd_test2.Models.TrackRace", b =>
                {
                    b.HasOne("apbd_test2.Models.Race", "Race")
                        .WithMany("TrackRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_test2.Models.Track", "Track")
                        .WithMany("TrackRaces")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("apbd_test2.Models.Race", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("apbd_test2.Models.Racer", b =>
                {
                    b.Navigation("RaceParticipations");
                });

            modelBuilder.Entity("apbd_test2.Models.Track", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("apbd_test2.Models.TrackRace", b =>
                {
                    b.Navigation("RaceParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
